SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS `act_traceip`;
CREATE TABLE `act_traceip` (
  `id` int(10) NOT NULL,
  `ua` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `ip` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `login` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `datetime` int(10) NOT NULL,
  `cpt` int(11) NOT NULL DEFAULT '0',
  `locked` smallint(1) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;


ALTER TABLE `act_traceip`
  ADD PRIMARY KEY (`id`),
  ADD KEY `ip` (`ip`);


ALTER TABLE `act_traceip`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
