SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS `act_prenom`;
CREATE TABLE `act_prenom` (
  `prenom` char(30) COLLATE latin1_general_ci NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

INSERT INTO `act_prenom` (`prenom`) VALUES
('?lisabeth-Anne'),
('?tiennette'),
('Ad?layde'),
('Ad?le'),
('Adela?de'),
('Adeline'),
('Adolphine'),
('Adrienne'),
('Agathe'),
('Agn'),
('Al?ide'),
('Al?is'),
('Albertine'),
('Alexandrine'),
('Alexise'),
('Alice'),
('Aline'),
('Alphone'),
('Alphonsine'),
('Am?lie'),
('Andr'),
('Ang?le'),
('Ang?lique'),
('Anne'),
('Anne-Marie'),
('Annette'),
('Antoinette'),
('Appoline'),
('Augusta'),
('Augustine'),
('Aur?lie'),
('Austine'),
('Barbe'),
('Benoite'),
('Bernardine'),
('Bertranne'),
('C?cile'),
('C?lestine'),
('C?line'),
('Caroline'),
('Catherine'),
('Charlotte'),
('Charlotte-Marie'),
('Christiane'),
('Christine'),
('Cl?mence'),
('Cl?mentine'),
('Claire'),
('Clara'),
('Claudine'),
('Clothilde'),
('Constance'),
('Constanse'),
('Constantine'),
('Cydonie'),
('Cyprienne'),
('D?sir'),
('Danielle'),
('Denise'),
('Dieudonn'),
('Doroth'),
('El?onore'),
('Elisabeth'),
('Elise'),
('Emerantine'),
('Emilie'),
('Ernestine'),
('Esther'),
('Eug?nie'),
('Eulalie'),
('Eur?lie'),
('F?licie'),
('F?licit'),
('Ferdinande'),
('Fleurie'),
('Florence'),
('Florentine'),
('Fran?oise'),
('Gabrielle'),
('Gemme'),
('Genevi?ve'),
('Germaine'),
('Gertrude'),
('Gervaise'),
('Gervaisine'),
('Ghislaine'),
('Gillette'),
('Guillemine'),
('Guyonne'),
('H?l?ne'),
('Hardouine'),
('Henriette'),
('Hiacinte'),
('Honorine'),
('Hortense'),
('Hyacinte'),
('Iabelle'),
('Ida'),
('Idelette'),
('Imelda'),
('Ir?ne'),
('Irma'),
('Isabelle'),
('Jacqueline'),
('Jacquine'),
('Jeanne'),
('Jeannette'),
('Jehanne'),
('Jenne'),
('Jos?phe'),
('Jos?phine'),
('Judith'),
('Julia'),
('Julie'),
('Julienne'),
('Juliette'),
('L?onie'),
('L?ontine'),
('Lancelotte'),
('Laure'),
('Laurence'),
('Louise'),
('Lucie'),
('M?lanie'),
('Mac'),
('Madeleine'),
('Magdelaine'),
('Magdeleine'),
('Maie'),
('Marguerite'),
('Margueritte'),
('Maria'),
('Mariane'),
('Marianne'),
('Marie'),
('Marie-Anne'),
('Marie-Catherine'),
('Marie-Charlotte'),
('Marie-Fran?oise'),
('Marie-Louise'),
('Marie-Magdelaine'),
('Marie-Perrine'),
('Marie-Ren'),
('Marie-Th?r?se'),
('Marthe'),
('Martine'),
('Mathilde'),
('Mathurine'),
('Melaine'),
('Michelle'),
('Monique'),
('Natalie'),
('Nathalie'),
('Nicolaine'),
('Nicole'),
('No?lle'),
('Ode'),
('Odile'),
('Olive'),
('Pasqui?re'),
('Paule'),
('Pauline'),
('Perrine'),
('Petronille'),
('Philippine'),
('Philom?ne'),
('Radegonde'),
('Reine'),
('Ren'),
('Roberte'),
('Rolande'),
('Rolende'),
('Rosa'),
('Rosalie'),
('Rose'),
('S?bastienne'),
('S?raphine'),
('Sainte'),
('Scholastique'),
('Scolastique'),
('Simone'),
('Sophie'),
('St?phanie'),
('Suzanne'),
('Th?r?se'),
('Thomasse'),
('Thorcile'),
('Thorisle'),
('Tugalle'),
('Urbaine'),
('Ursule'),
('Valentine'),
('Vallerie'),
('Victoire'),
('Victorie'),
('Victorine'),
('Virginie');


ALTER TABLE `act_prenom`
  ADD PRIMARY KEY (`prenom`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
