SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS `act_params`;
CREATE TABLE `act_params` (
  `param` varchar(25) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `groupe` varchar(30) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `ordre` int(11) NOT NULL DEFAULT '100',
  `type` char(1) COLLATE latin1_general_ci NOT NULL DEFAULT 'C',
  `valeur` text COLLATE latin1_general_ci,
  `listval` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `libelle` varchar(250) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `aide` text COLLATE latin1_general_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

INSERT INTO `act_params` (`param`, `groupe`, `ordre`, `type`, `valeur`, `listval`, `libelle`, `aide`) VALUES
('EA_VERSION', 'Hidden', 100, 'C', '3.2.2', '', 'N° de version du logiciel', ''),
('EA_MAINTENANCE', 'Hidden', 100, 'N', '0', '', 'Indique si l\'accès est bloqué (1) pour maintenance', ''),
('EA_LSTBACKUP', 'Hidden', 100, 'C', 'N:0000-00-00;M:0000-00-00;D:0000-00-00;V:0000-00-00;U:0000-00-00;P:0000-00-00;', '', 'Mémorise la date des derniers backups complets réalisés N M D V U P', ''),
('SITENAME', 'Affichage', 100, 'C', 'Expoactes', '', 'Nom du site principal', 'Nom du site utiliés dans le cartouche de tête et dans les mails automatiques.'),
('SITE_URL', 'Affichage', 110, 'C', '/', '', 'URL du site principal', 'URL relative ou absolue du site web principal (utilisée pour créer un lien de retour vers le site principal).'),
('MAX_PAGE', 'Affichage', 200, 'N', '100', '', 'Eléments affichés par page', 'Nombre références d\'actes affichés par pages dans les recherches'),
('MAX_PAGE_ADM', 'Affichage', 210, 'N', '100', '', 'Eléments par page (mode administration)', 'Nombre références d\'actes affichés par pages dans les recherches en mode administration'),
('MAX_PATR', 'Affichage', 250, 'N', '200', '', 'Basculement en mode alphabétique', 'Nombre de patronymes à partir duquel on passe en mode de regroupement alphabétique ABC..Z'),
('MAX_PATR_ADM', 'Affichage', 260, 'N', '200', '', 'Mode alphabétique (mode administration)', 'Nombre de patronymes à partir duquel on passe en mode de regroupement alphabétique ABC..Z (en mode administration)'),
('SHOW_DATES', 'Affichage', 300, 'B', '1', '', 'Accueil : affichage des dates min. et max.', 'Détermine si les dates minimales et maximales des actes d\'une commune sont affichées dans la page d\'accueil d\'Expoactes.'),
('SHOW_DISTRIBUTION', 'Affichage', 310, 'B', '0', '', 'Accueil : lien vers la distribution des années', 'Détermine si l\'icône faisant le lien vers les statistiques des actes par années est présent dans le tableau public. NB : L\'affichage de lien nécessite aussi que le paramètre précédent soit activé.'),
('SHOW_ALLTYPES', 'Affichage', 320, 'B', '1', '', 'Accueil : afficher tous les types d\'actes', 'Détermine si la page d\'accueil affiche le tableau résumé des quatre types d\'actes (par défaut) ou d\'un seul.'),
('SHOW_NULL', 'Deleted', 510, 'B', '0', '', 'Actes : afficher les zones non complétées', 'Détermine si les zones vides sont affichées ou non dans les fiches détaillées des actes'),
('SHOW_DEPOSANT', 'Deleted', 520, 'B', '1', '', 'Actes : afficher les noms des déposants', 'Détermine si le nom de la personne ayant chargé les actes dans la base est affiché au bas du détail des actes.'),
('ANNEE_TABLE', 'Affichage', 400, 'L', '0', '0 - Toujours date détaillée;1 - Années si non connecté;2 - Années si non déposant;3 - Années dans tous les cas', 'Tables : affichages des années seulement', 'L\'affichage des tables d\'actes présente en principe la date complète des actes. Si vous souhaitez limiter cet affichage à l\'année seulement pour les visiteurs non connectés ou les non déposants (niveau=4), il suffit de sélectionner la valeur appropriée.'),
('JPG_SI_LOGIN', 'Affichage', 550, 'B', '0', '', 'Actes : images seulement si login', 'Lorsque cette case est cochée, le lien vers les images d\'actes (zone \"Libre\") n\'apparait que lorsque le visiteur est connecté; dans le cas contraire le texte \"image privée\" est affiché.'),
('AVERTISMT', 'Affichage', 600, 'T', '', '', 'Texte d\'avertissement', 'Texte facultatif à afficher en tête de la première page au dessus de l\'inventaire des communes.'),
('PIED_PAGE', 'Affichage', 620, 'T', '', '', 'Pied de page', 'Texte libre du pied de page : peut contenir un texte ou un script javascript (pour un compteur de visiteurs par exemple).'),
('PUB_ZONE_MENU', 'Affichage', 720, 'T', '', '', 'Zone de pub sous le menu', 'Il est possible de faire afficher sous le menu un texte quelconque tels qu\'une publicité pour vos activités. Il peut aussi être utilisé pour afficher un cadre de publicités type \"Google Adsens\". Cette zone doit être complétée par du HTML valide. Le style .pub_menu peut être utilement créé dans la CSS.'),
('COOKIE_MESSAGE', 'Affichage', 800, 'T', 'Les cookies nous permettent de faciliter la navigation et l\'usage du site, de personnaliser le contenu et les annonces et d\'analyser notre trafic. L\'usage du site implique l\'acceptation de ces cookies.', '', 'Message acceptation des cookies', 'Ce message, affiché tous les ans, annonce l\'utilisation des cookies sur le site. Vous pouvez personnaliser le message en fonction des services activés (google analytics, publicité, ...)'),
('COOKIE_URL_INFO', 'Affichage', 810, 'T', 'http://www.allaboutcookies.org/fr/', '', 'URL d\'une page sur les cookies', 'Cette page permet au visiteur d\'en savoir plus sur les cookies. Il peut s\'agir d\'une page interne au site ou externe.'),
('COOKIE_STYLE', 'Affichage', 820, 'L', '1', '1 - en haut, foncé;2 - en haut, clair ;3 - en bas, foncé;4 - en bas, clair ;5 - flottant, foncé;6 - flottant, clair', 'Style du message cookies', 'La boîte de message pour l\'acceptation des cookies peut avoir un fond clair ou foncé et être positionnée en haut, en bas ou \"flottante\".'),
('FULL_URL', 'Système', 200, 'B', '0', '', 'Affichage des URL sans arguments', 'Cette option permet d\'intégrer les arguments d\'une requête directement dans l\'URL de façon à favoriser l\'indexation de vos pages par les moteurs de recherche (Google p. ex). Attention, il est possible que cette option ne soit pas supportée par votre hébergeur.'),
('URL_JPG', 'Système', 300, 'T', '/img_act/', '', 'URLs des images d\'actes', 'Cette zone contient l\'URL relative ou absolue désignant le répertoire où sont rangées les images des actes citées dans la rubrique LIBRE (fichers avec extension .JPG ou .TIF). Il est possible de faire appel à des images situées dans plusieurs sites différents en les prifixant par un code de votre choix. Dans ce cas, l\'URL par défaut sera suivie d\'un ; puis, pour chaque site d\'image du code préfixe des images suivi > et ensuite de l\'URL absolue du site. Exemple de contenu : /img_act/;CODE1>http://site1.fr/;CD2>http://site2.be/images/'),
('LEVEL_JPG_PRIVE', 'Système', 310, 'L', '5', '4 - Actes;5 - Import Nimègue;6 - Import CSV;7 - Spécial;8 - Gestionnaire;9 - Administrateur', 'Niveau d\'accès aux images privées', 'L\'accès aux images d\'actes dans les sous-répertoires PRIVE du repertoire ci-dessus n\'est autorisé qu\'aux visiteurs connectés avec le niveau précisé ici'),
('UPLOAD_DIR', 'Système', 350, 'C', '_upload', '', 'Répertoire de stockage temporaire des chargements', 'Les fichiers CSV téléchargés pour l\'ajout d\'actes sont transférés tempoarairement dans le répertoire \"_upload\" situé lui-même dans le répertoire \"admin\". Si l\'hébergement oblige à utiliser un autre répertoire pour les téléchargement, il faut alors spécifier le chemin d\'accès de ce répertoire avec ce paramètre'),
('LOGINTYPE', 'Deleted', 400, 'B', '1', '', 'Login avec cookies et cryptage', 'Spécifie le mode de login qui peut être soit avec usage de cookies (permet le crypatge et la mémorisation des codes d\'accès et la déconnexion), soit le login via HTTP Header. Le mode via cookies doit être préféré chaque fois que c\'est possible.'),
('META_DESCRIPTION', 'Système', 510, 'T', '', '', 'Description du site (pour balise meta tags)', 'Description de votre site pour les moteurs de recherche. Notez que cette description est automatiquement postfixée par le titre de la page généré par le logiciel.'),
('META_KEYWORDS', 'Système', 520, 'T', 'généalogie, dépouillement, actes, tables, patronymes, BMS, NMD, commune, paroisse', '', 'Mots-clés du site (pour balise meta tags)', 'Liste de mots clés pour les moteurs de recherche (à séparer par des virgules). Notez que cette description est automatiquement postfixée par le titre de la page généré par le logiciel.'),
('GOOGLE_ANA_CODE', 'Système', 525, 'C', '', '', 'ID de suivi Web Google Analytics (exemple : UA-12345-1)', 'Votre code identifiant pour le suivi automatiques des statistiques de votre site via Google Analytics : Voir http://www.google.com/analytics/fr-FR/index.html'),
('INCLUDE_HEADER', 'Système', 530, 'T', '', '', 'Autres élements pour le header HTML', 'Eléments à inclure dans le header de chaque page HTML.<br />Attention : ces éléments doivent respecter strictement la syntaxe xHTML.'),
('SHOW_ACCES', 'Système', 900, 'B', '1', '', 'Affichage des conditions d\'accès privé', 'Détermine si l\'item \"Conditions d\'accès\" apparaît dans le menu public.'),
('SHOW_RSS', 'Système', 910, 'B', '1', '', 'Affichage de l\'icône RSS', 'Détermine si le lien avec icône du flux RSS est affiché dans le cadre des statistiques.'),
('MAX_EXEC_TIME', 'Système', 920, 'N', '30', '', 'Temps (en sec.) maximum de création d\'une page', 'Ce temps permet d\'obliger ExpoActes à limiter le temps d\'exécution des opérations de chargement, de backup, ... plus strictement que ce qui est détecté en se basant sur les paramètres PHP.'),
('MAX_SELECT_REC', 'Système', 930, 'N', '0', '', 'Nombre maximal d\'actes sélectionnés par requête', 'Ce nombre permet de limiter les requêtes lors des exports et backups lorsque le serveur MySQL rejette les requêtes contenant \"trop\" (selon lui) de lignes en résultat. <br />Un valeur de 25000 est alors souvent judicieuse mais rend impossible les exports supérieurs à ce nombre de lignes. <br />La valeur 0 annule cette limite.'),
('EA_ERROR', 'Système', 990, 'L', '0', '0 - Aucune erreur affichée (Normal);1 - Erreurs uniquement;2 - Erreurs + problèmes mineurs;3 - Toutes remarques;4 - Debugging MySQL', 'Niveau d\'affichage des erreurs et problèmes rencontrés', 'Ce paramètre permet en cas de recherche de solution à un problème, de faire apparaître les erreurs détectées par PHP. En fonctionnement normal, toujours choisir 0.'),
('CHERCH_TS_TYP', 'Recherche', 100, 'B', '1', '', 'Recherche par défaut sur tous types d\'actes', 'Cette option provoque l\'affichage d\'une liste de sélection du type des actes dans la boîte de recherche de la page d\'accueil et n\'autorise que la sélection d\'un type d\'acte à la fois dans les recherches avancées. Cette option permet donc d\'alléger le travail du moteur de recherche.'),
('RECH_DEF_TYP', 'Recherche', 150, 'L', '1', '1 - Exacte;2 - au Début;3 - à la Fin;4 - est Compris dans;5 - Sonore', 'Comparaison proposée par défaut', 'Détermine le mode de comparaison qui est proposé par défaut pour la recherche avancée. Les deux premiers sont nettement plus économes en ressources serveur que les trois suivants.'),
('RECH_MIN', 'Recherche', 200, 'N', '3', '', 'Longueur minimale du mot recherché', 'Détermine le nombre minimum de caractères sur lesquels doit porter une recherche.'),
('RECH_LEVENSHTEIN', 'Recherche', 500, 'L', '1', '0 - Désactivée;1 - Dans rechercher avancée;2 - Dans recherche rapide', 'Activation de la recherche Levenshtein', 'Ce paramètre indique si l\'algorithme est actif et si c\'est le cas, où doit apparaître le lien vers la page de recherche spécifique. Les valeurs possibles sont :  0 : la recherche levenshtein est totalement désactivée (et donc interdite à tout utilisateur); 1 : la recherche levenshtein est active et accessible via un lien situé dans la page de recherche avancée; 2 : la recherche levenshtein est active et accessible via un lien situé dans la boîte de recherche rapide.'),
('LEVEL_LEVENSHTEIN', 'Recherche', 510, 'L', '5', '1 - Communes;2 - Patronymes;3 - Tables;4 - Actes;5 - Import Nimègue;6 - Import CSV;7 - Spécial;8 - Gestionnaire;9 - Administrateur', 'Niveau d\'accès pour la rech. Levenshtein', 'Ce paramètre détermine le niveau d\'accès nécessaires aux utilisateurs pour pouvoir utiliser la recherche Levenshtein. Par défaut, ce niveau est 8 afin de réserver l\'usage aux administrateurs seulement. Ce niveau ne peut pas être inférieur au niveau PUBLIC_LEVEL.'),
('SECURITE_TIME_OUT_PHP', 'Recherche', 520, 'N', '5', '', 'Secondes réservées pour terminer une recherche', 'La recherche levenshtein peut nécessiter plusieurs dizaines de seconde de calcul lorsque la requête est trop vague. Or la plupart des serveurs limitent le temps de calcul (souvent à 30 sec) puis abandonnent la tâche. Pour éviter cela, le paramètre SECURITE_TIME_OUT_PHP spécifie le nombre de seconde de sécurité que le système se réserve afin de stopper proprement la recherche et de signaler à l\'utilisateur que sa recherche est trop complexe.'),
('CRIT_RECH_COUPLES', 'Recherche', 530, 'L', '3', '2 - ° des enfants;3 - ° & + des enfants;4 - °, + & x des enfants', 'Etendue des recherches sur les couples', 'Ce paramètre permet d\'étendre ou de restreindre les possibilités de recherches levenshtein sur les couples. Les valeurs peuvent aller de 2 à 4 :* 2 : Autorise la recherche des mariages de ces couples et des naissances des enfants de ces couples;* 3 : Idem 2 + les décès des enfants de ces couples ;* 4 : Idem 3 + recherches des mariages d\'enfants de ces couples;'),
('ECLAIR_AUTORISE', 'Recherche', 950, 'B', '1', '', 'Publier la liste éclair pour Généanet', 'Cette liste éclair permet à Généanet d\'indexer facilement les données de votre base pour en favoriser l\'usage par les généalogistes. Cette page page est visible à l\'adresse <a href=../eclair.php>eclair.php</a>'),
('ECLAIR_MAX_ROW', 'Recherche', 960, 'N', '10000', '', 'Nombre maximum d\'actes par liste éclair', 'Si la cration d\'une liste éclair prend trop de temps, ce paramètre permet de réduire le nombre d\'actes qui sont considérés pour les listes partielles.'),
('ECLAIR_LOG', 'Recherche', 965, 'B', '1', '', 'Journalisation des requêtes éclair', 'Lorsque la case est cochée, chaque appel de la liste éclair génère une ligne dans un fichier log rangé dans le répertoire _log.'),
('PUBLIC_LEVEL', 'Utilisateurs', 100, 'L', '1', '1 - Communes;2 - Patronymes;3 - Tables;4 - Actes', 'Niveau d\'accès public (sans login)', 'Le paramètres PUBLIC_LEVEL détermine le niveau d\'accès qui est autorisé en mode \"public\" c\'est-à-dire sans devoir fournir un login et un mot de passe.Les valeurs admises sont :1 = Accès public à la liste des communes uniquement;2 = Accès public aux patronymes; 3 = Accès public aux \"tables\" avec noms, prénoms et dates des actes;4 = Accès public aux détails des actes.'),
('USER_AUTO_DEF', 'Utilisateurs', 150, 'L', '0', '0 - Manuel par les gestionnaires;1 - Semi-automatique avec approbation;2 - Automatique sans approbation', 'Enregistrement des utilisateurs', 'Mode d\'enregistrement des utilisateurs et distribution des logins :<br />\n0 : Enregistrement manuel par le gestionnaire ou l\'administrateur;<br />\n1 : Enregistrement semi-automatique via formulaire avec approbation obligatoire par l\'administrateur ou un gestionnaire;<br />\n2 : Enregistrement tout automatique sur base des valeurs par défaut de gestion des points. Attention : le fonctionnement du serveur mail doit être parfait.'),
('USER_AUTO_LEVEL', 'Utilisateurs', 160, 'L', '4', '3 - Tables seulement;4 - Voir les actes;5 - Import NIMEGUE;6 - Import CSV', 'Niveau d\'accès après enregistement auto.', 'Niveau d\'accès attribué automatiquement aux personnes qui s\'enregistrent directement sur le site.'),
('AUTO_CAPTCHA', 'Utilisateurs', 180, 'B', '1', '', 'Affichage d\'un code captcha', 'Affiche un code de contrôle anti-spam sous forme d\'image avec des chiffres dissimulés. Interdit l\'encodage automatique a des robots.<br />(Nécessite la librairie GD sur l\'hébergement)'),
('TEST_EMAIL_UNIC', 'Utilisateurs', 190, 'B', '1', '', 'Vérifier l\'unicité des adresses mail', 'Interdit l\'enregistrement de deux utilisateurs avec la même adresse email.'),
('LIMITE_EXPIRATION', 'Utilisateurs', 194, 'C', '', '', 'Date limite ou durée des comptes', 'Expiration des comptes visiteurs : Soit une date fixe JJ/MM/AAAA, soit une durée en JOURS à compter de la date de création.'),
('DUREE_EXPIR', 'Utilisateurs', 195, 'N', '90', '', 'Délai avant suppression des comptes expirés', 'Détermine le nombre de jours qui sont comptés pour pouvoir sélectionner un compte comme expiré lors de la suppression des comptes. NB : La suppression n\'est pas automatique.'),
('USER_ZONE_LIBRE', 'Utilisateurs', 197, 'C', '', '', 'Libellé de la zone libre', 'Une zone de texte peut être ajoutée au formulaire d\'inscription des utilisateurs lorsque ce libellé est non vide. Cette zone est aussi reprise dans la fiche utilisateur.'),
('CHANGE_PW', 'Utilisateurs', 200, 'L', '5', '1 - Communes;2 - Patronymes;3 - Tables;4 - Actes;5 - Actes sans limite;6 - Import data;7 - Spécial;8 - Gestionnaire;9 - Administrateur', 'Niveau pour pouvoir changer de mot de passe', 'Détermine le niveau d\'accès à partir duquel un utilisateur enregistré a le droit de modifier lui-même son mot de passe. Par défaut, CHANGE_PW vaut 1.Si plusieurs utilistateurs doivent partager le même code d\'accès et le même mot de passe (par exemple au niveau 4), il est prudent d\'en interdire la modification.'),
('GEST_POINTS', 'Utilisateurs', 500, 'L', '0', '0 - Désactivée;1 - Recharge manuelle;2 - Recharge automatique', 'Mode de gestion des points', 'Détermine le régime de gestion des points par défaut:\n        0 : aucune gestion des points pour aucun membre;\n        1 : gestion des points avec recharge manuelle. C\'est l\'adminsitrateur qui distribue les points et lui seul;\n        2 : gestion des points avec recharge automatique. La recharge s\'effectuera automatiquement pour tous les membres auxquel l\'administrateur affectera le régime 2 (valeur par défaut).'),
('PTS_PAR_PER', 'Utilisateurs', 510, 'N', '10', '', 'Points donnés à chaque recharge automatique', 'Détermine le nombre de points qui sont attribués aux membres à chaque recharge automatique.'),
('DUREE_PER_P', 'Utilisateurs', 520, 'N', '7', '', 'Nombre de jours entre deux recharges auto.', 'Détermine le nombre de jours qui séparent deux recharges automatiques.'),
('RECH_ZERO_PTS', 'Utilisateurs', 530, 'B', '1', '', 'Recherche autorisée si points épuisés', 'Autorise ou interdit la réalisation de recherches lorsque le stock de points est épuisé.'),
('DEPOSANT_LEVEL', 'Utilisateurs', 600, 'L', '6', '4 - Visiteur enregistré;5 - Actes sans limites;6 - Import data', 'Niveau des déposants', 'Niveau à partir duquel un utilisteur peut être déposant (et apparaître dans les liste des déposants lors de l\'import par l\'administrateur).'),
('TXT_CONDIT_USAGE', 'Utilisateurs', 700, 'T', '', '', 'Texte des conditions d\'utilisation', 'Ce texte est affiché et doit être explicitement approuvé par les nouveaux utilisateurs pour pouvoir créer un compte. Si cette zone reste vide, aucun texte n\'est afiché et aucune confirmation n\'est demandée.'),
('LOC_MAIL', 'Mail', 110, 'C', 'tenochtitlan77@hotmail.com', '', 'Adresse mail de l\'administrateur', 'Votre propre adresse e-mail : cette adresse sera l\'adresse d\'envoi par défaut ET le destinataire des messages internes pour l\'administrateur (gestion des comptes, fitrage IP, ...)'),
('EMAIL_SIGN_ERR', 'Mail', 112, 'C', '', '', 'Mail pour signalements d\'erreur', 'Cette adresse mail désigne la personne qui recevra les signalements d\'erreur dans les actes. L\'absence d\'adresse désactive la fonction de signalement.'),
('EMAIL_CONTACT', 'Mail', 115, 'C', '', '', 'Mail destinataire du formulaire de contact', 'Cette adresse mail désigne la personne qui recevra les messages via le formulaire de contact. L\'absence d\'adresse désactive l\'affichage du formulaire de contact.'),
('EXTERN_MAIL', 'Mail', 120, 'B', '0', '', 'Envoyer les mails via un serveur externe', 'Indique au logiciel qu\'il ne peut faire appel à la fonction mail intégrée de PHP qui est normalement préconfigurée par l\'hébergeur (0).Si celle-ci ne fonctionne pas, il faut activer ce paramètre (1) et configurer les autres paramètres pour utiliser un compte mail personnel dont le serveur SMTP doit cependant être accessible au départ du lieu d\'hébergement.'),
('SMTP_HOST', 'Mail', 200, 'C', '', '', 'Serveur SMTP', 'Adresse du serveur SMTP'),
('SMTP_ACC', 'Mail', 210, 'C', '', '', 'Login du compte mail', 'Votre code d\'accès pour le compte mail (si le serveur SMTP exige une authentification de l\'utilisateur)'),
('SMTP_PASS', 'Mail', 220, 'C', '', '', 'Mot de passe du compte SMTP', 'Votre mot de passe pour le compte mail (si le serveur SMTP exige une authentification de l\'utilisateur)'),
('LOC_HOST', 'Mail', 250, 'C', '', '', 'Nom du serveur d\'origine des mails', 'Nom du serveur local expédiant les mails'),
('MAIL_NEWUSER', 'Mail', 510, 'T', 'Bonjour #PRENOM#,\r\n\nUn compte vient d\'être créé pour vous permettre de vous connecter au site #NOMSITE# :\r\n\r\n\n#URLSITE#\r\n\nVotre login : #LOGIN#\r\n\nVotre mot de passe : #PASSW#\r\n\r\n\nCordialement,\r\n\r\n\nVotre webmestre.', '', 'Message à un nouvel utilisateur', 'Texte par defaut du mail envoyé aux nouveaux utilisateurs lors de la création du compte par l\'administrateur'),
('MAIL_AUTOUSER', 'Mail', 520, 'T', 'Bonjour #PRENOM#,\r\n\nMerci de vous être enregistré(e) sur le site #NOMSITE#.\r\n\r\n\nPour valider votre adresse email et rendre votre compte opérationnel, vous devez ACTIVER le compte avec le lien suivant :\r\n\r\n\n#URLVALID#\r\n\nAu besoin votre code d\'activation est : #KEYVALID#\r\n\r\n\nCordialement,\r\n\r\n\nVotre webmestre.', '', 'Message de demande d\'activation <br /> SANS validation', 'Texte automatique du mail envoyé aux candidats utilisateurs qui viennent de créer leur compte d\'accès. <br /><b>Attention à bien y laisser le code #URLVALID#</b> qui permettra l\'activation du compte.'),
('MAIL_VALIDUSER', 'Mail', 530, 'T', 'Bonjour #PRENOM#,\r\n\nMerci de vous être enregistré(e) sur le site #NOMSITE#.\r\n\r\n\nPour valider votre adresse email, vous devez ACTIVER le compte avec le lien suivant :\r\n\r\n\n#URLVALID#\r\n\nAu besoin votre code d\'activation est : #KEYVALID#\r\n\r\n\nVotre demande de compte sera alors examinée par le gestionnaire du site dans les meilleurs délais.\r\n\r\n\nCordialement,\r\n\r\n\nVotre webmestre.', '', 'Message de demande d\'activation <br /> AVEC validation', 'Texte automatique du mail envoyé aux candidats utilisateurs qui viennent de créer leur compte d\'accès. <br /><b>Attention à bien y laisser le code #URLVALID#</b> qui permettra l\'activation du compte. Le texte doit aussi indiquer que le compte devra être approuvé par l\'administrateur.'),
('MAIL_APPROBATION', 'Mail', 540, 'T', 'Bonjour #PRENOM#,\r\n\r\n\nVotre demande de compte d\'utilisateur du site #NOMSITE# a été approuvée.\r\n\r\n\nVotre compte \"#LOGIN#\" est à présent opérationnel à l\'adresse\r\n \n#URLSITE#\r\n\r\n\nCordialement,\r\n\r\n\nVotre webmestre.', '', 'Message d\'approbation d\'un utilisateur', 'Texte par defaut du mail envoyé aux utilisateurs lors de l\'approbation de leur compte par l\'administrateur'),
('MAIL_REFUS', 'Mail', 550, 'T', 'Bonjour #PRENOM#,\r\n\r\n\nVotre demande de compte d\'utilisateur du site #NOMSITE# n\'a pu être approuvée.\r\n\r\n\nCordialement,\r\n\r\n\nVotre webmestre.', '', 'Message de refus d\'un utilisateur', 'Texte par defaut du mail envoyé aux candidats utilisateurs refusés par l\'administrateur'),
('LEVEL_MAIL_LOGIN', 'Protection', 50, 'L', '10', '5 - Actes sans limite ;6 - Import données ;7 - Spécial;8 - Gestionnaire;9 - Administrateur;10 - Jamais', 'Niveaux avec login confirmé par mail', 'Ce paramètre indique le niveau à partir duquel le login est systématiquement confirmé par un envoir de mail.'),
('TIP_FILTRER', 'Protection', 100, 'L', '0', '0 - Aucun filtrage;1 - Compter toutes le pages;2 - Compter les actes seulement', 'Utiliser l\'anti-aspirateur IP', 'Détermine si le module de filtrage des adresses IP doit être activé ou non et sur quels types de pages. Ce module permet de bloquer les visiteurs qui chargeraient en masse des actes sur le site.'),
('TIP_MAX_PAGE_COUNT', 'Protection', 105, 'N', '25', '', 'Nombre maximum par période', 'Au dela de ce nombre de pages ou d\'actes vus par un même visiteur (même adresse IP) l\'adresse sera bloquée.'),
('TIP_DUREE', 'Protection', 110, 'N', '1', '', 'Durée de la période en minutes', 'Durée en minutes de la période sur laquelle est compté le nombre de pages ou d\'actes vus.'),
('TIP_MAIL_TO', 'Protection', 200, 'C', '', '', 'Destinataire du mail d\'alerte', 'Adresse mail de la personne qui recevra les notifications lorsque des adresses IP seront bannies.'),
('TIP_MSG_BAN', 'Protection', 300, 'T', 'Adresse IP interdite pour abus !', '', 'Texte renvoyé aux IP bannies', 'Texte qui sera affiché aux visiteurs ayant une des adresses IP bannies.'),
('TIP_AUTOFREE', 'Protection', 360, 'N', '0', '', 'Durée du blocage en jours', 'Nombre de jours où l\'adresse reste bloquéef.<br /> ATTENTION : 0 = Pas de déblocage automatique.'),
('TIP_ALERT', 'Protection', 400, 'N', '1', '', 'Nbre d\'alertes avant blocage', 'Nombre de pages portant un avertissement avant blocage définitif. <br /> 0 = Aucun avertissement.'),
('TIP_MSG_ALERT', 'Protection', 420, 'T', 'Attention : Vous ne pouvez plus consulter que #RESTE# actes avant le #TERME#.', '', 'Texte d\'alerte avant blocage', 'Texte qui sera affiché aux visiteurs approchant du nombre limite de pages par période. Le texte peut etre enrichi avec les codes #IPCLIENT# :Adresse IP, #COMPTE# : Nombre de pages/actes déjà vus, #RESTE# : Nombre de pages/actes restant, #TERME# : Date et heure de renouvellement du comptage.'),
('TIP_MODE_ALERT', 'Protection', 425, 'L', '1', '1 - Message en haut de page;2 - Boîte de dialogue; 3 - Message + Boîte de dialogue', 'Mode d\'affichage des alertes', 'Détermine la manière dont les alertes sont affichées : <br />\n		1 : Message de couleur rouge affiché en haut de page; <br />\n		2 : Boîte de dialogue javascript avec bouton OK à cliquer obligatoirement; <br />\n		3 : Combinaison des deux méthodes précédentes.'),
('TIP_LEVEL_NO_IP_TEST', 'Protection', 450, 'L', '9', '5 - Actes sans limite;6 - Import données;7 - Spécial;8 - Gestionnaire;9 - Administrateur', 'Niveaux exemptés du contrôle IP', 'Ce paramètre indique le niveau à partir duquel le visiteur enregistré est libéré du contrôle du nombre de page par minute. NB : le niveau 5 est TOUJOURS exempté !'),
('TIP_WHITELIST', 'Protection', 500, 'T', '', '', 'Agents affranchis', 'Liste des signatures des agents qui sont autorisés (typiquement les signatures de robots). Les signatures doivent être séparées par des VIRGULES.'),
('TIP_MEMOWHITE', 'Protection', 550, 'B', '0', '', 'Mémoriser les IP auto-affranchies', 'Mémorise et affiche les IP qui sont affranchies automatiquement via la liste des agents autorisés.'),
('GEO_MODE_PUBLIC', 'Géoloc', 100, 'L', '4', '1 - Carte seulement;2 - Tableau seulement;3 - Carte affichée et tableau masqué;4 - Tableau affiché et carte masquée;5 - Carte et tableau affichés', 'Contenu de la page d\'accueil', 'Détermeine si la carte des communes est affichée, ou le tableau détaillé ou ces deux éléments à la fois.'),
('GEO_HAUT_CARTE', 'Géoloc', 120, 'N', '500', '', 'Hauteur de la carte en pixels', 'Valeur classique = 500 pixels'),
('GEO_ZOOM_INITIAL', 'Géoloc', 200, 'N', '0', '', 'Niveau de zoom initial', 'Détermine le niveau de zoom initial (généralement entre 6 et 10) ou 0 si automatique.'),
('GEO_CENTRE_CARTE', 'Géoloc', 210, 'C', '', '', 'Centrage forcé de la carte sur', 'Permet de préciser la localité qui doit occuper le centre de la carte. DOIT être une des communes ou paroisse géolocalisée.'),
('GEO_ZOOM_DEGROUPAGE', 'Géoloc', 220, 'N', '10', '', 'Niveau de zoom dégroupage', 'Détermine le niveau de zoom où les points seront toujours dégroupés (ordinairement 10 à 12).'),
('GEO_LOCALITE', 'Géoloc', 300, 'B', '1', '', 'Géolocalisation des localités', 'Fournit un lien pour localiser chaque localité à partir des tables.');


ALTER TABLE `act_params`
  ADD PRIMARY KEY (`param`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
